CC = gcc
CFLAGS = -Wall -Wextra -std=c99

STACKCLIENT_SRC = ADVANCED/PROGRAM_DESIGN/stackclient.c ADVANCED/PROGRAM_DESIGN/stackADT.c
STACKCLIENT_BIN = stackclient

.PHONY: all run clean

all: $(STACKCLIENT_BIN)

$(STACKCLIENT_BIN): $(STACKCLIENT_SRC) ADVANCED/PROGRAM_DESIGN/stack-ADT.h
	$(CC) $(CFLAGS) $(STACKCLIENT_SRC) -o $(STACKCLIENT_BIN)

run: $(STACKCLIENT_BIN)
	./$(STACKCLIENT_BIN)

clean:
	rm -f $(STACKCLIENT_BIN)
